{% set version = "1.19.0" %} 
{% set posix = 'm2-' if win else '' %}

package:
  name: r-network
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/network_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/network/network_{{ version }}.tar.gz
  sha256: fd12a007fb16411ef386102f3ebb582ffc5b6798a7eb83858cb8601e1a152012

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-statnet.common           # [build_platform != target_platform]
    - r-magrittr                 # [build_platform != target_platform]
    - r-tibble                   # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-magrittr
    - r-statnet.common >=4.5
    - r-tibble
  run:
    - r-base
    - r-magrittr
    - r-statnet.common >=4.5
    - r-tibble

test:
  commands:
    - $R -e "library('network')"           # [not win]
    - "\"%R%\" -e \"library('network')\""  # [win]

about:
  home: http://statnet.org/
  license: GPL-2.0-or-later
  summary: Tools to create and modify network objects.  The network class can represent a range of relational data types, and supports arbitrary vertex/edge/graph attributes.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
