travis:
  secure:
    BINSTAR_TOKEN: rbwS7ifHjIvtfxqUs53ozv+JZrNlbEU/tOBKxFnFrGFmH2rAHc1q60EVX14WkHRJ8+5oMy75pY1y5TYuTZUe+6fJkQLSJAU3mSjQS5D32oz0RZZGYrpmbmdoVdde0BSfbqp7RZy+K+5cqxGsAoIFnhFnuI+LEq8y+4q3P1nQs68sGC8gyhgVYBPRI4LOCfK6Y33OzKftl4S7eoJttdfugpBLCcCkFadj+idBCAyswRupRhP2zt0NZ33QVOmtbyvShx9UQmW+lDo0dSyHDaSJtJpdsC/0TaeMoP77aJ4Mn/WoI2q8NjssFOm9VCg+2zaYwvwHzP686YIJiSYkQW5au/mcFeBFIKN8AeeBxyihLNmFGWEDaJzKn1+rCa/MXR7paoQpPP7zyECi4KzuoaAWObKbMGIyczLCRhVbh9VtVUbilE7Br/WYlmYy3eQCUDPUnNTSNg08uCMYP0tBq4F4sQX6718ag5PgaTEPuS4vi7owssBwokrt2nC2GSjL9ZK0HrZKHgfvjDCqJBw/1yAGcBatwFfHo6Di0qYz1cmupp8xbauKR3nRyVikcbbGd92UBK94TiUNVskodtxPO0ZfcrN80vtM2NJ4xu/uFcvmqkf4V1zb8hUn/S9q2ayCZJjNfMDCRR7dfgJbwgqTjVM2pMnjF+IVs5f1WV4/1Eg9anY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
