travis:
  secure:
    BINSTAR_TOKEN: eSQ9YQldvsqKdQf9LkafLzHq37QG3yhtdpG/NEJUKHE5oTugyNM4NhBuTohBdFJA+89pgYtLceWGsRWS7RywlfW0yXP2X06xzAAes7IIRoOzZQwUuEm6u6PGWX2WFwfnG4TVJdQphF33Mf7X9oj5FgDxQRVNHiVTyjjWMU15vRr2F7S7s7BlMlIvoM5phcHYqRGLNCoDK4xDYZPSohi/PG76xFKv+Hrf7wbMnFLyKh55VPtOxoKuxMCyWULb5MXYNv5bB33NEEKMX8YGAEeR4hf79/71Pp7vUVDLkB7PhEXC9LpnjZo7m1fDhdpSdT33pTJgW3IY674Nzkc+xMV8qq2lh+2wC7Lzl2jsdYfXpVqPjLXWaUeoctROxwlYo8GMNOOt0JiT/F7J9I5hm0B47KqUl5q6My7cD7iv13yp7iItlcDA0ZIDcf3dAR+k9l8M9U3fMlr5U72ImiPqvqb/59vdozUnAMr6dJCn579A0BopY55LNP8EFUDValcU6gn0wrN7LtqDY/5xJ6lI0pHi00SOHHEL2xSKKB8fRJ0ETGyMutn/hUTWWXzU1HD1CNhjXJiCNmog8iijSNpFXttIqVsGgf0oIIJQjWwsx1N85bYO9WBQlAdx0yjkypQU0r4bJ4dTfuRD5xy52ucARK2XIbltGP8++QPclDxLvfPsy/s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
