appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: JoMJC6KaRqOzYv7In11TcyO5iExz8pMclRfZ+rP4ePfRf+XjyfzV21oz/CmgbEeGj4XZwZ5R546ca3wzPSrgHnHTfmeMlmgrxRc3LdGw4O6Kta1C58zUGYFACipUGf//mXEDZWPV9uI3ox+E4nNvmFwcNzlY9huhsAA7wHv/hKmTbKsuOv/jYompoY4jWKdZ5iBAoUOFqbmcFgF9Kvn9qyJzp+Goxj4LkfY3jeKsGlULnH9LbR9R5e/tKcSlqFHv0U3aGaZuzMdysZoJPoZcWYx6Cn9nWYahx8/15tetzlptaUpz+ZGoDnyU+A/1rhnhx5ahhavWgbiHZdIT53EXToRC++C0L+0MOU8EKrj6FMppSq63VYMk8pTUcT2rKm0ny4ij7GC92hspNH2gfHAb3XQF7qrXDm0vWdfgDLeryIBSyOcms/w+roVicW2LRPBYy7fxfZL+n3OAvU1nCsmWaifT40vFqTMhhPPOpKkLGzYrvD/HtIqayw2W0bcJFxNXNkXCL7LTZT9mGNnH82AL5B334tmXzC90jqltrZlz88VN1WgogsKAHJtRexTWQaQvqAKLlte8tk8MRas/fIrXx681NqFSRUYay2jhep3LPWi4Jf0w5SMfXd6kqVf5fWs4rV2iarmPERAzaGpm4SzIhiSYGHtR2Wj/bBFieeWvpTk=}
bot:
  automerge: true
